### ISSUE TITLE
Conda environment

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/dMRIharmonization#93]
Hi @suheyla2 , opening this issue here so as not to bother the original user--did you build [this](https://github.com/pnlbwh/dMRIharmonization/issues/90#issuecomment-2216314985) environment at the time of your comment? It does not build today.

**Comment by tashrifbillah** [comment]
Tashrif's test-in-progress environment:

```
dipy
pandas
scikit-image
git+https://github.com/mhe/pynrrd.git
git+https://github.com/pnlbwh/conversion.git
```

It is quite open ended.

**Comment by tashrifbillah** [comment]
Corresponding conda environment:

```yml
name: harmonization

channels:
    - conda-forge
    - pnlbwh

dependencies:
    - python>=3.0
    - nibabel
    - pandas
    - scipy
    - scikit-image
    - ants
    - pip
    - pip:
        - git+https://github.com/mhe/pynrrd.git
        - git+https://github.com/pnlbwh/conversion.git
```
